backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "news"
    label: "Новини"
    folder: "news"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Текст", name: "body", widget: "markdown"}
